### PR TITLE
Allow custom file types for source media files

### PR DESCRIPTION
**Pull request by ericpony**
Hello rprieto, thank you for developing this module. It is neat and handy! For my personal purpose, I had to add options to it so that the gallery can include custom file types such as webm and ogg. I guess other users will also find these options useful.

### CODE REVIEW

**Comment by rprieto** [comment]
Thanks a lot for the PR, `ogg` and `webm` support is a great idea. Ideally thumbsup should support all media formats, so I'll add them in by default (and `ogv` too). The rule should be "if it's supported by exiftool and ffmpeg then it should work out of the box".

Where you're not lucky is that I just extracted a big part of thumbsup to https://github.com/thumbsup/node-thumbsup-collection, where all the globbing/extension logic lives.

Are you happy if I add these in manually for now? It will be part of the `v2.0.0` release.

**Comment by ericpony** [comment]
My suggestion (as can be seen in the commit) is to avoid hardcoding all supported file types. In my case, I don't care about exif and my target visitors use Chrome, so it's ok for me to include mkv files in my gallery even though they are not standard HTML5 videos. I will be happy if you can add more flexibility to the design of `node-thumbsup-collection` in this respect ;-)

**Comment by rprieto** [comment]
Thanks. Let me try to understand the exact use case. Currently thumbsup puts every file through `ffmpeg` or `graphicsmagick` to generate thumbnails and web-friendly sizes. This means it really only supports photos and videos, for example if you specify `--photo-extensions=jpg,txt` it would generate an error when picking up a `txt` file.

- Would it be enough if it always processed *all* known formats? For example:

```js
const PHOTO_EXT = ['bmp','gif','jpg','jpeg','png','tif','tiff','webp']
const VIDEO_EXT = ['3gp','flv','m2ts','mkv','mp4','mov','mts','ogg','ogv','webm']
```

- If you want to be able to specific other extensions, what would they be?
- Is your requirement that you want certain files to go through unprocessed, e.g. the `mkv` file displayed as-is (not resized, not converted to mp4). Currently **all** files are processed/resized and converted to JPEG, unless the user clicks "Download original" which obviously downloads the original :smile:

**Comment by ericpony** [comment]
Sorry it's my mistake. I was thinking that videos are displayed as-is, but the fact is thumbsup converts everything to mp4/jpg. So it is ok to hardcode all file types supported by ffmpeg/graphicsmagick. Thank you for your response!

**Comment by rprieto** [comment]
No problem. Apart from generating the 100x100 thumbnails for both photos and videos, the main reason it processes them is to create the "large" size which is more web-friendly, e.g. ~200kb instead of 3Mb for a photo, or 10Mb instead of 100Mb for a video.

If your use case is that
1. you only care about local browsing, or your users always have fast internet
2. you know they will be on Chrome which supports many formats like `mkv`, and you know you won't have any non-supported files (e.g. `bmp`)

Then we could look at another feature which is to skip the "large" generation altogether, and always use the originals. This would make building the gallery faster. It would depend on #54 happening, to make that much easier to implement.

**Pull request closed without merging**
